- name: Create four docker containers
  hosts: docker-host
  connection: local
  become: yes
  gather_facts: no 
#
# Create docker container with Nexus repository by using image from DockerHub
#
  tasks:
    - name: Create container
      docker_container:
        name: nexus-container
        image: sonatype/nexus3
        published_ports:
          - "8081:8081"
        volumes:
          - /nexus-data
        state: started
#
#
