version: '3.3'
#
services:
  traefik:
    # The official v2.0 Traefik docker image
    image: traefik:v2.0
    # Enables the web UI and tells Traefik to listen to docker
    command: 
      --api.insecure=true 
      --providers.docker=true
      --providers.docker.exposedbydefault=false
      --entrypoints.web.address=:80
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock:ro
#
  whoami-red:
    image: containous/whoami
    container_name: whoami-red 
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami-red.rule=(Host(`whoami.docker.localhost`) && Path(`/red`))"
      - "traefik.http.routers.whoami-red.entrypoints=web"
#
#
  whoami-blue:
    image: containous/whoami
    container_name: whoami-blue
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami-blue.rule=(Host(`whoami.docker.localhost`) && Path(`/blue`))"
      - "traefik.http.routers.whoami-blue.entrypoints=web"
#
#
  whoami-green:
    image: containous/whoami
    container_name: whoami-green
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami-green.rule=(Host(`whoami.docker.localhost`) && Path(`/green`))"
      - "traefik.http.routers.whoami-green.entrypoints=web"
#
#
